# Generated by Django 6.0.3 on 2026-03-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='MesaModel',
            fields=[
                ('id_mesa', models.AutoField(db_column='id_mesa', primary_key=True, serialize=False)),
                ('numero_mesa', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='libre', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='NoticiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'noticias',
            },
        ),
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=50)),
                ('monto_total', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_mesa', models.CharField(blank=True, max_length=10, null=True)),
                ('comentarios', models.TextField(blank=True, max_length=500, null=True)),
                ('total', models.FloatField(default=0.0)),
                ('estado', models.CharField(default='PENDIENTE', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='RolModel',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='DetallePagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pago', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='users.pagomodel')),
            ],
            options={
                'db_table': 'detalle_pagos',
            },
        ),
        migrations.AddField(
            model_name='pagomodel',
            name='pedido',
            field=models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='users.pedidomodel'),
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.FloatField()),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='users.categoriamodel')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='InventarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad_minima', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='users.productomodel')),
            ],
            options={
                'db_table': 'inventarios',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='users.pedidomodel')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='users.productomodel')),
            ],
            options={
                'db_table': 'detalle_pedidos',
            },
        ),
        migrations.CreateModel(
            name='CarritoItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.FloatField()),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='users.productomodel')),
            ],
            options={
                'db_table': 'carrito_items',
            },
        ),
        migrations.CreateModel(
            name='PromocionModel',
            fields=[
                ('id_promocion', models.AutoField(db_column='id_promocion', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('descuento', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productos', models.ManyToManyField(db_table='promocion_productos', related_name='promociones', to='users.productomodel')),
            ],
            options={
                'db_table': 'promociones',
            },
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_reserva', models.DateTimeField()),
                ('hora', models.CharField(max_length=10)),
                ('numero_personas', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mesa', models.ForeignKey(db_column='mesa_id', on_delete=django.db.models.deletion.CASCADE, to='users.mesamodel')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='reserva',
            field=models.ForeignKey(blank=True, db_column='reserva_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.reservamodel'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(db_column='id_rol', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.rolmodel')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_asignados', to='users.user'),
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='user',
            field=models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cliente', to='users.user'),
        ),
        migrations.AddField(
            model_name='pagomodel',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.CreateModel(
            name='HorarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.CharField(max_length=5)),
                ('hora_fin', models.CharField(max_length=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_empleado', to='users.user')),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
    ]
