# Generated by Django 6.0.3 on 2026-03-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_insumos_recetas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepagomodel',
            name='pago',
        ),
        migrations.DeleteModel(
            name='CarritoItemModel',
        ),
        migrations.DeleteModel(
            name='DetallePagoModel',
        ),
    ]
