# Generated by Django 6.0.3 on 2026-03-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_eliminar_carrito_item_detalle_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomodel',
            name='codigo_pedido',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
